wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.35
    code_path: code/src/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
annotation_file:
  desc: null
  value: /home/datta/lab/HPE3D/src/data/debug_h36m17.h5
batch_size:
  desc: null
  value: 3
beta:
  desc: null
  value: 1
cuda:
  desc: null
  value: true
device:
  desc: null
  value: cpu
epochs:
  desc: null
  value: 1
exp_name:
  desc: null
  value: run_1
fast_dev_run:
  desc: null
  value: true
ignore_images:
  desc: null
  value: false
image_path:
  desc: null
  value: /home/datta/lab/HPE_datasets/h36m/
latent_dim:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
log_interval:
  desc: null
  value: 1
logger:
  desc: null
  value: null
n_joints:
  desc: null
  value: 16
num_workers:
  desc: null
  value: 4
pin_memory:
  desc: null
  value: false
pretrained:
  desc: null
  value: false
resume_pt:
  desc: null
  value: 0
save_dir:
  desc: null
  value: /home/datta/lab/checkpoints
seed:
  desc: null
  value: 400
step:
  desc: null
  value: 0
train_last_block:
  desc: null
  value: false
train_subjects:
  desc: null
  value:
  - 1
  - 5
  - 6
  - 7
  - 8
val_subjects:
  desc: null
  value:
  - 9
  - 11
variant:
  desc: null
  value: 2
